name: ddt

channels:
  - conda-forge
  - memex
  - anaconda
  - vida-nyu

dependencies:
    - elasticsearch
    - supervisor
    - meld3
    - dateutil
    - cython >=0.22
    - ddt-word2vec
    - maven
    - nltk
    - scipy
    - numexpr >=2.4
    - scikit-learn >=0.18.1
    - pyelasticsearch >=1.2
    - cherrypy
    - requests
    - ache ==latest
    - jinja2
    - functools32
    - networkx=1.11
    - nodejs
    - futures
