name: ddt

channels:
  - conda-forge
  - memex
  - anaconda
  - vida-nyu

dependencies:
    - dateutil
    - cython >=0.22
    - nltk
    - scipy
    - numexpr >=2.4
    - scikit-learn >=0.18.1
    - pyelasticsearch >=1.2
    - cherrypy
    - requests
    - ache ==0.9.0
    - functools32
    - jinja2
    - nodejs
    - futures
    - openjdk
    - joblib
